/** Initial repository files generated for each project. */

export function projectMd(name, kickoff, ownerName) {
  return `# ${name}

> Project record generated by Project OS for Codex. Git history is the source of truth for progress.

## Who this is for
${kickoff.forWhom || '(Not provided)'}

## Intended outcome
${kickoff.goal || '(Not provided)'}

## Acceptance criteria
${(kickoff.acceptance || []).map((item) => `- [ ] ${item}`).join('\n') || '- (Not provided)'}

## Out of scope for this iteration
${kickoff.notDoing || '(Not defined)'}

## Owner
${ownerName || '(Not assigned)'}
`;
}

export const AGENTS_MD = `# AI execution rules and boundaries

Every AI agent operating through a short-lived project credential or the legacy project key must follow these rules:

1. Read HANDOFF.md, PROJECT.md, AGENTS.md, PROGRESS.md, and ISSUES/ before changing anything.
2. Work in one small vertical slice at a time. Do not broaden the scope without human direction.
3. Completion means the result was verified on the real target surface. Run the relevant type checks and build, and review light and dark UI when applicable.
4. Stay inside the assigned workspace and project. Never access another workspace, project, database, or credential.
5. Payment, deletion, permissions, publication, production deployment, and rollback always require explicit human approval.
6. Never request, print, commit, or copy passwords, tokens, provider keys, or other secrets.
7. After each verified slice, call project_os_append_progress. Record a technical result, a plain-language result, why it was done, the benefit, the concrete verification performed, and the next action.
8. Do not invent users, data, tests, adoption, or completion states. If evidence is missing, say so.

## Progress write

Preferred: call the MCP tool project_os_append_progress.

Legacy REST: POST /api/agent/v1/projects/{projectId}/events
headers: Authorization: Bearer <short-lived project credential>; Idempotency-Key: <stable retry key>
body: {
  "message": "Verified technical result",
  "plainMessage": "Result a non-technical owner can understand",
  "why": "Why this slice was done now",
  "benefit": "Concrete user or maintainer benefit",
  "verification": "The concrete command, URL, screenshot, or artifact checked",
  "progressTo": 40,
  "nextStep": "The next concrete action"
}
`;

export function progressMd(progress = 0) {
  return `# Progress\n\nCurrent progress: ${progress}%\n\n(This file is updated by recorded progress events. Do not edit it manually.)\n`;
}

/** Build the durable handoff document written into the project repository. */
export function handoffPackageMd({ rec, recentLog = [], problems = [], note, toOwnerName }) {
  const acceptance = (rec.kickoff.acceptance || []).map((item) => `- [ ] ${item}`).join('\n') || '- (Not provided)';
  const logLines =
    recentLog
      .slice(0, 8)
      .map((event) => {
        const progress =
          event.progressFrom !== null && event.progressTo !== null
            ? ` (${event.progressFrom}% -> ${event.progressTo}%)`
            : '';
        return `- ${new Date(event.at).toLocaleString('en-US')} · ${event.actor} · ${event.plainMessage || event.message}${progress}`;
      })
      .join('\n') || '- No progress events yet';
  const problemLines = problems.length ? problems.map((problem) => `- ${problem}`).join('\n') : '- No recorded issues';

  return `# Handoff · ${rec.name}

> Safe handoff: ${toOwnerName || 'the next owner'} creates a new short-lived credential for the agent. The agent reads this document and the project context before continuing.
> Generated: ${new Date().toLocaleString('en-US')}

## Current state in one sentence
Progress is ${rec.progress}%. Next action: ${rec.nextStep || '(Not defined)'}.

## Audience and intended outcome
${rec.kickoff.forWhom || '(Not provided)'}
${rec.kickoff.goal || '(Not provided)'}

## Acceptance criteria
${acceptance}

## Out of scope
${rec.kickoff.notDoing || '(Not defined)'}

## Recent recorded work
${logLines}

## Known issues
${problemLines}

## Next action
${rec.nextStep || '(Add one concrete next action before work resumes)'}

## Handoff note
${note || '(None)'}

## Safety reminder
Follow AGENTS.md. Destructive actions require human approval, every verified slice needs a progress record, and work is complete only after verification on the real target surface.
`;
}

function section(title, items = [], empty = '(Not provided)') {
  const rows = (Array.isArray(items) ? items : [items]).map((item) => String(item || '').trim()).filter(Boolean);
  return [`## ${title}`, rows.length ? rows.map((item) => `- ${item}`).join('\n') : empty, ''].join('\n');
}

export function retroSummaryMd({ rec, answers = {} }) {
  return [
    `# Retrospective · ${rec.name}`,
    `> Generated: ${new Date().toLocaleString('en-US')}`,
    '',
    '## Project goal',
    rec.kickoff.goal || '(Not provided)',
    '',
    '## Intended audience',
    rec.kickoff.forWhom || '(Not provided)',
    '',
    section('1. What remained uncertain or poorly understood?', answers.uncertainties),
    section('2. What was the largest omission?', answers.omissions),
    section('3. If this fails in three months, what is the most likely reason?', answers.failureRisks),
    section('4. What single addition would make this category-leading?', answers.leadingFeatures),
    section('5. What alternative approach would have been more efficient?', answers.betterWays),
    section('6. What worked well?', answers.wins),
    section('7. What went wrong or caused avoidable rework?', answers.pitfalls),
    section('8. What should change next time?', answers.improvements),
    '## Follow-up',
    '- Reusable lessons and methods were added to the workspace knowledge base.',
    '- Search this retrospective before starting a similar project.',
    '',
  ].join('\n');
}
